### ISSUE TITLE
Potential issue with mode selector overwriting buttons

### ISSUE THREAD

**Issue by DunkyDaMonkey** [pbutterworth/astralpool_chlorinator#2]
Problem: 
After using the manual button to stop the chlorinator to perform a backwash, the integration pushed the chlorinator back in my auto. 

Work around: 
Make sure to set the selector to off. 

I haven't looked at the code for the selector yet, and when I get a chance i'll do a bit more testing with the chlorinator too.

**Comment by pbutterworth** [comment]
@DunkyDaMonkey 
Few questions:
1. Was the system in Auto before you started?
2. Had you used the mode selector in HA recently, before starting?
3. Do you have any automations that target the select entity?
4. How long was it between setting manual on the machine, and it going back to auto, approximately?

There are not many code paths that lead to calling `write_gatt_char`. It seems so unlikely that this got called to trigger your pump to go back on. I wonder if there is some strange condition where there is an active BT connection, while the physical interface is being operated, causing it to revert to an earlier state or something...

**Comment by DunkyDaMonkey** [comment]
1) Yes the system was set to auto, I had done this while I was at the skimmer box. As at low speeds I can pull the suction plate out.
2) Yes,  probably with in 2-3minutes earlier
3) No, I have no automations that use the new integration.
4) I would guess 10-20sec, as I was using the manual button, as soon as it came to a full stop I was switching the backwash selector. 

I didn't that the time to reproduce it, it totally could have been human error, maybe I hit the button an extra time or something. 

I'll have a play tomorrow, with the selector and the manual button and see if I can reproduce anything similar.

**Comment by DunkyDaMonkey** [comment]
Well, I had a play with it today, all sort of combinations, I couldn't reproduce, so I'm going to chalk this up to my own human error, I must have hit the button an extra time. 

Thank you for looking into it, I'll close it out with this comment.
