### ISSUE TITLE
HomeAssistant updated bluetooth-Data-Tools to 0.4.0 

### ISSUE THREAD

**Issue by DunkyDaMonkey** [pbutterworth/astralpool_chlorinator#3]
Bump bluetooth-data-tools to 0.4.0 ([@bdraco](https://github.com/bdraco) - [#91442](https://github.com/home-assistant/core/pull/91442))
Use bluetooth data tools for address conversion in esphome ([@bdraco](https://github.com/bdraco) - [#91443](https://github.com/home-assistant/core/pull/91443))

The new Bluetooth Data Tools has been committed to HA 2023.5, Manifest.json needs requirement update if 0.3.1 has been updated. 

https://github.com/pbutterworth/astralpool_chlorinator/blob/f1083a9bee17d0fa98994ce24a45ce62bafec813/custom_components/astralpool_chlorinator/manifest.json#L16

`  "requirements": ["bluetooth-data-tools>=0.3.1", "pychlorinator>=0.2.3"],`

**Comment by pbutterworth** [comment]
Updated the requirement to 0.4.0.
